spring:
  application:
    name: web
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8087

db:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/library?serverTimezone=UTC
  username: root
  password: admin
